using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/TBLGroundMovement")]
public partial class TBLGroundMovement : BGEntityGo
{
	public override BGMetaEntity MetaConstraint
	{
		get
		{
			return MetaDefault;
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4655728081626509110,7815188617546194328));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	public new System.String name
	{
		get
		{
			return _name[Entity.Index];
		}
		set
		{
			_name[Entity.Index] = value;
		}
	}
	public System.Single maxJumpHeight
	{
		get
		{
			return _maxJumpHeight[Entity.Index];
		}
		set
		{
			_maxJumpHeight[Entity.Index] = value;
		}
	}
	public System.Single minJumpHeight
	{
		get
		{
			return _minJumpHeight[Entity.Index];
		}
		set
		{
			_minJumpHeight[Entity.Index] = value;
		}
	}
	public System.Single moveSpeed
	{
		get
		{
			return _moveSpeed[Entity.Index];
		}
		set
		{
			_moveSpeed[Entity.Index] = value;
		}
	}
	public System.Single timeToJumpApex
	{
		get
		{
			return _timeToJumpApex[Entity.Index];
		}
		set
		{
			_timeToJumpApex[Entity.Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName __name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name
	{
		get
		{
			if(__name==null || __name.IsDeleted) __name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5261059805820861611,11377872366047856279));
			return __name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat __maxJumpHeight;
	public static BansheeGz.BGDatabase.BGFieldFloat _maxJumpHeight
	{
		get
		{
			if(__maxJumpHeight==null || __maxJumpHeight.IsDeleted) __maxJumpHeight=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4627730202242280645,16514233397850234797));
			return __maxJumpHeight;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat __minJumpHeight;
	public static BansheeGz.BGDatabase.BGFieldFloat _minJumpHeight
	{
		get
		{
			if(__minJumpHeight==null || __minJumpHeight.IsDeleted) __minJumpHeight=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5279511563479695397,14976648306491816086));
			return __minJumpHeight;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat __moveSpeed;
	public static BansheeGz.BGDatabase.BGFieldFloat _moveSpeed
	{
		get
		{
			if(__moveSpeed==null || __moveSpeed.IsDeleted) __moveSpeed=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(5181927467511130381,16251533208221606575));
			return __moveSpeed;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldFloat __timeToJumpApex;
	public static BansheeGz.BGDatabase.BGFieldFloat _timeToJumpApex
	{
		get
		{
			if(__timeToJumpApex==null || __timeToJumpApex.IsDeleted) __timeToJumpApex=(BansheeGz.BGDatabase.BGFieldFloat) MetaDefault.GetField(new BGId(4710218893620350228,13510807895866224036));
			return __timeToJumpApex;
		}
	}
}
